version: "3.9"

services:
  web:
    build: .
    container_name: wagtail_web
    ports:
      - "3000:3000"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      DJANGO_SUPERUSER_PASSWORD: supersecret
